CREATE TABLE `sys_user` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`company_id` BIGINT(20) NULL DEFAULT NULL,
	`office_id` BIGINT(20) NULL DEFAULT NULL,
	`login_name` VARCHAR(50) NULL DEFAULT NULL,
	`password` VARCHAR(50) NULL DEFAULT NULL,
	`no` VARCHAR(50) NULL DEFAULT NULL,
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`phone` VARCHAR(50) NULL DEFAULT NULL,
	`mobile` VARCHAR(50) NULL DEFAULT NULL,
	`user_type` CHAR(50) NULL DEFAULT NULL,
	`login_ip` VARCHAR(50) NULL DEFAULT NULL,
	`login_date` TIMESTAMP NULL DEFAULT NULL,
	`create_by` BIGINT(20) NULL DEFAULT NULL,
	`create_date` TIMESTAMP NULL DEFAULT NULL,
	`update_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`update_by` BIGINT(20) NULL DEFAULT NULL,
	`remarks` VARCHAR(400) NULL DEFAULT NULL,
	`del_flag` CHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;